version: '3.8'

services:
  laud-us:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laud-us-app
    ports:
      - "5173:5173"
    environment:
      - RUNNING_IN_DOCKER=true
    volumes:
      # Sincroniza a pasta de worklist local do host com o container
      - /Users/matheuskistenmackerpires/Documents/OrthancServer/db/WorklistsDatabase:/app/pacs-worklist
    extra_hosts:
      # Permite que o container conecte a serviços no localhost do host (como o Orthanc local na porta 8042/8043)
      - "host.docker.internal:host-gateway"
    restart: always
